language: node_js
node_js:
  - node
sudo: false
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_script:
  - snyk auth $SNYK_TOKEN
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  only:
    - master