language: node_js
node_js:
  - 4
sudo: false
addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
branches:
  only:
    - master